### ISSUE TITLE
As a user, I want to be able to add a new course to the app

### ISSUE THREAD

**Issue by piamanns** [ohtutraininghub/traininghub#18]
### Tasks:
- #39
- #40 
- #55 
- #41 
- #42

### Acceptance criteria:
- [ ] User is able to add course when logged in

**Comment by joonas-a** [comment]
Implement tags

**Comment by joonas-a** [comment]
Improve form input validation to include past dates

**Comment by joonas-a** [comment]
Move course addition to it's own page
