### ISSUE TITLE
As a user, I want to be able to view the details of a course

### ISSUE THREAD

**Issue by mmoila** [ohtutraininghub/traininghub#37]
### Tasks:
- #39
- #40 
- #55 
- #41 
- #43 

### Acceptance criteria:
- [ ] User is able to open details of course by clicking it when logged in

**Comment by mmoila** [comment]
- Details 
  - course date(s) (start date, ending date)
  - name
  - description (links to materials)
  - student capacity

**Comment by joonas-a** [comment]
Show details in either own tab / backdrop / modal
