### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by DeeCaaD** [ohtutraininghub/traininghub#52]
- Unhandled errors with Sentry: https://docs.sentry.io/platforms/javascript/guides/nextjs/

- Handled errors
  - visualize: https://mui.com/material-ui/react-snackbar/#customization
  - standardized error API response on handled failures
    -  for example `error-response:` `error-message: string` `error-type: ErrorTypeEnum: error | warning | info | success`, where error type enum might change how its shown in frontend
- error tsx

**Comment by tommivk** [comment]
I think we should also create a custom `error.tsx` or `global-error.tsx` page so that e.g. navbar will be rendered when unhandled error happens:
https://nextjs.org/docs/app/building-your-application/routing/error-handling

**Comment by DeeCaaD** [comment]
Yep, that can come from Sentry also
